### ISSUE TITLE
Modelo 3D da Franzininho WiFi

### ISSUE THREAD

**Issue by andremdaraujo** [Franzininho/franzininho-wifi-makeymakey#10]
@FBSeletronica, conforme falamos, poderia por favor disponibilizar o modelo 3D da Franzininho WiFi? Para podermos resolver as dimensões do shield.
Obrigado!

**Comment by FBSeletronica** [comment]
Opa André. Vou providenciar. Obrigado

**Comment by FBSeletronica** [comment]
@andremdaraujo tem um step na pasta do projeto: https://github.com/Franzininho/Franzininho-WiFi/tree/main/Franzininho-WIFI-kicad

Veja se ajuda ou se precisa de algum ajuste.

Vou ver se crio um componente dela com todos os arquivos.

**Comment by andremdaraujo** [comment]
![image](https://user-images.githubusercontent.com/94403601/185750599-13e0a312-33c1-47fa-a4ba-402f151647b3.png)

Valeu @FBSeletronica, consegui exportar um .STEP da placa pelo KiCad e adicionei no projeto.

**Comment by andremdaraujo** [comment]
![image](https://user-images.githubusercontent.com/94403601/185756985-b2781c9d-a223-4110-ae16-2bf684001a16.png)

Melhorei o modelo 3D adicionando os conectores (macho na Franzininho WiFi e fêmea no shield)

Na imagem os conectores estão distanciados para ficar mais claro, mas vou deixar encostados no projeto.

Removi os furos do layout da Franzininho WiFi, conforme falamos.

**Comment by FBSeletronica** [comment]
@andremdaraujo adicionei novos modelos 3D da placa em: https://github.com/Franzininho/Franzininho-WiFi/tree/main/Franzininho-WIFI-kicad/3D
