### ISSUE TITLE
Conectores Grove

### ISSUE THREAD

**Issue by andremdaraujo** [Franzininho/franzininho-wifi-makeymakey#11]
Conectores para Grove atualmente estão ficando um pouco para fora da placa. Precisamos determinar se isso é aceitável (acho que assim não haveria problema, mas se houver temos que aumentar a placa para baixo):

![image](https://user-images.githubusercontent.com/94403601/185766585-45793d9a-7e84-4605-b0fe-89c40458e575.png)

![image](https://user-images.githubusercontent.com/94403601/185766597-9319a92a-c367-4f67-96e9-4232e990900b.png)

**Comment by FBSeletronica** [comment]
@andremdaraujo podemos manter dessa forma. Penso que assim ajudará na hora de encaixar o conector.
