### ISSUE TITLE
Pad múltiplo para buzzer

### ISSUE THREAD

**Issue by andremdaraujo** [Franzininho/franzininho-wifi-makeymakey#13]
@FBSeletronica, não consegui localizar as medidas para aquele pad com múltiplas furações para o buzzer. Por favor, conseguiria infromar as medidas que utilizou no projeto da placa de laboratório? Obrigado!

**Comment by FBSeletronica** [comment]
@andremdaraujo fiz um footprint para o buzzer e adicionei na pasta LIB: https://github.com/Franzininho/franzininho-wifi-makeymakey/tree/main/HARDWARE/KICAD/LIB/FRANZININHO_WIFI.pretty
