### ISSUE TITLE
Conectores para Garra Jacaré

### ISSUE THREAD

**Issue by FBSeletronica** [Franzininho/franzininho-wifi-makeymakey#5]
1 - Acredito que podemos aumentar o furo para a garra jacaré. Um furo de 4 mm já permitirá trabalhar melhor com as garras.
2 - Vamos pensar na nomenclatura para esses conectores

**Comment by andremdaraujo** [comment]
1 - Ajustado
2 - Sugestões: "TOUCHx"; "PADx"; "KEYx"; notas musicais: C, D, E, F, G, A, B, C; ...
