### ISSUE TITLE
Dimensão do Shield

### ISSUE THREAD

**Issue by FBSeletronica** [Franzininho/franzininho-wifi-makeymakey#7]
@andremdaraujo o que acha  de deixar a placa um pouco maior que a franzininho WiFi. Penso algo em torno de 1mm de cada lado.

Considere também arredondar os cantos da placa.

**Comment by andremdaraujo** [comment]
Ajustado

![image](https://user-images.githubusercontent.com/94403601/183322282-4dc108df-dece-45fa-a91b-1639891b4630.png)

![image](https://user-images.githubusercontent.com/94403601/183322295-2792ee9c-34a8-4e17-8c68-3ba392bf1e67.png)
