### ISSUE TITLE
Pinos de expansão

### ISSUE THREAD

**Issue by FBSeletronica** [Franzininho/franzininho-wifi-makeymakey#8]
@andremdaraujo podemos deixar os conectores na parte traseira da placa.  

Também dividir na pinagem 2 canais I2C.

Talvez possamos deixar os pinos que sobrarem em uma barra de pinos para uso geral. O que acha?

**Comment by andremdaraujo** [comment]
@FBSeletronica excelentes ideias! Conforme falamos, vou colocar os conectores I2C na traseira, conectores de 90° saindo para baixo. Dividi em 2 pares de conectores para I2C1 e I2C2. Estou adicionando os pinos de I/O que sobraram num barramento.

![image](https://user-images.githubusercontent.com/94403601/183311742-2d437196-fe71-40fc-b61b-1ae89cccd7c6.png)

**Comment by FBSeletronica** [comment]
@andremdaraujo excelente. Obrigado
